services:
  - type: web
    name: digitalmarketingbiz-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_SHEET_WEBAPP_URL
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
