services:
  - type: web
    name: digitalmarketingbiz-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:flask_app --timeout 120 --preload
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_SHEET_WEBAPP_URL
        sync: false
      - key: ROOT_URL
        value: https://digitalmarketingbiz-bot.onrender.com
